simulation:
  n_loci: 10
  n_pop: 5000
  n_gen: 10
  n_iter: 1000000
  random_seed: 42

snps:
  default_maf: 0.20
  snp_maf:
    rs1: 0.65
    rs2: 0.35
    rs3: 0.05

phenotype:
  name: "height"
  heritability: 0.45
  causal_snps:
    rs1: 0.5

mating_model:
  type: "assortative"
  pairs:
    - male_snp: rs1 
      female_snp: rs1
      correlation: 0.95
