# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pheno_h2 <- function() {
    .Call(`_amsimr_pheno_h2`)
}

pheno_comp_mean <- function(component_type) {
    .Call(`_amsimr_pheno_comp_mean`, component_type)
}

pheno_comp_var <- function(component_type) {
    .Call(`_amsimr_pheno_comp_var`, component_type)
}

pheno_comp_cor <- function(component_type) {
    .Call(`_amsimr_pheno_comp_cor`, component_type)
}

pheno_comp_xcor <- function(component_type) {
    .Call(`_amsimr_pheno_comp_xcor`, component_type)
}

pheno_latent_h2 <- function() {
    .Call(`_amsimr_pheno_latent_h2`)
}

pheno_latent_comp_mean <- function(component_type) {
    .Call(`_amsimr_pheno_latent_comp_mean`, component_type)
}

pheno_latent_comp_var <- function(component_type) {
    .Call(`_amsimr_pheno_latent_comp_var`, component_type)
}

pheno_latent_comp_cor <- function(component_type) {
    .Call(`_amsimr_pheno_latent_comp_cor`, component_type)
}

pheno_latent_comp_xcor <- function(component_type) {
    .Call(`_amsimr_pheno_latent_comp_xcor`, component_type)
}

#' Create a new SimulationConfig object reference
#'
#' @return A new SimulationConfig instance
#'
.SimulationConfig__new <- function() {
    .Call(`_amsimr_SimulationConfig__new`)
}

#' Configure simulation parameters.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#' @param n_generations Integer. Number of generations to simulate.
#' @param n_individuals Integer. Number of individuals in the population.
#' @param output_dir String. Output directory to write data out to.
#' @param random_seed Integer. Seed used by random number generator.
#'
#' @return Self, for method chaining.
#'
.SimulationConfig__simulation <- function(ptr, n_generations, n_individuals, output_dir, random_seed) {
    .Call(`_amsimr_SimulationConfig__simulation`, ptr, n_generations, n_individuals, output_dir, random_seed)
}

#' Configure genome parameters.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#' @param n_loci Number of genetic loci simulated in the population.
#' @param locus_maf Vector of locus MAFs
#' @param locus_recombination Vector of locus recombination probabilities
#' @param locus_mutation Vector of locus mutation probabilities
#'
#' @return Self, for method chaining
#'
.SimulationConfig__genome <- function(ptr, n_loci, locus_maf, locus_recombination, locus_mutation) {
    .Call(`_amsimr_SimulationConfig__genome`, ptr, n_loci, locus_maf, locus_recombination, locus_mutation)
}

#' Configure phenome parameters.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#' @param n_phenotypes Number of phenotypes modelled in the population.
#' @param names Vector of phenotype names.
#' @param n_causal_loci Number of causal loci for each phenotype.
#' @param h2_genetic Narrow-sense phenotype heritabilities.
#' @param h2_environmental Phenotype environmental component variances.
#' @param h2_vertical Phenotype vertical component variances.
#'
#' @return Self, for method chaining
#'
.SimulationConfig__phenome <- function(ptr, n_phenotypes, names, n_causal_loci, h2_genetic, h2_environmental, h2_vertical, genetic_cor, environmental_cor) {
    .Call(`_amsimr_SimulationConfig__phenome`, ptr, n_phenotypes, names, n_causal_loci, h2_genetic, h2_environmental, h2_vertical, genetic_cor, environmental_cor)
}

#' Specify a random mating regime.
#'
#' @return Self, for method chaining.
#'
.SimulationConfig__random_mating <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__random_mating`, ptr)
}

#' Specify an assortative mating regime.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#' @param mate_cor Column-major double trait cross-correlation matrix
#' @param tol_inf Termination threshold for annealing routine.
#' @param n_iterations Maximum number of steps performed in annealing routine.
#' @param temp_init Initial temperature of annealing routine
#' @param temp_decay Temperature decay parameter of annealing routine
#'
#' @return Self, for method chaining
#'
.SimulationConfig__assortative_mating <- function(ptr, mate_cor, tol_inf = NULL, n_iterations = NULL, temp_init = NULL, temp_decay = NULL) {
    .Call(`_amsimr_SimulationConfig__assortative_mating`, ptr, mate_cor, tol_inf, n_iterations, temp_init, temp_decay)
}

#' Configure simulation metrics
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#' @param metrics List of metric objects to attach to the simulation.
#'
#' @return Self, for method chaining.
#'
.SimulationConfig__metrics <- function(ptr, metrics) {
    .Call(`_amsimr_SimulationConfig__metrics`, ptr, metrics)
}

#' Get the number of generations.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__n_generations <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__n_generations`, ptr)
}

#' Get the number of individuals.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__n_individuals <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__n_individuals`, ptr)
}

#' Get the number of loci.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__n_loci <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__n_loci`, ptr)
}

#' Get the output directory.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__output_dir <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__output_dir`, ptr)
}

#' Get the RNG seed.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__random_seed <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__random_seed`, ptr)
}

#' Get the locus MAF vector.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__locus_maf <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__locus_maf`, ptr)
}

#' Get the locus recombination probabilities.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__locus_recombination <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__locus_recombination`, ptr)
}

#' Get the locus mutation probabilities.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__locus_mutation <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__locus_mutation`, ptr)
}

#' Get the number of phenotypes.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__n_phenotypes <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__n_phenotypes`, ptr)
}

#' Get the phenotype names.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__phenotype_names <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__phenotype_names`, ptr)
}

#' Get the phenotype names.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__n_causal_loci <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__n_causal_loci`, ptr)
}

#' Get the narrow-sense phenotype heritabilities.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__h2_genetic <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__h2_genetic`, ptr)
}

#' Get the phenotype environmental component variances.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__h2_environmental <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__h2_environmental`, ptr)
}

#' Get the phenotype vertical component variances.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__h2_vertical <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__h2_vertical`, ptr)
}

#' Get the phenotype genetic component correlation matrix.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__genetic_cor <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__genetic_cor`, ptr)
}

#' Get the phenotype environmental component correlation matrix.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__environmental_cor <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__environmental_cor`, ptr)
}

#' Get the mating correlation matrix.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__mate_cor <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__mate_cor`, ptr)
}

#' Get the annealing tolerance threshold.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__tol_inf <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__tol_inf`, ptr)
}

#' Get the maximum number of annealing iterations.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__n_iterations <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__n_iterations`, ptr)
}

#' Get the initial annealing temperature.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__temp_init <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__temp_init`, ptr)
}

#' Get the annealing temperature decay parameter.
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
.SimulationConfig__temp_decay <- function(ptr) {
    .Call(`_amsimr_SimulationConfig__temp_decay`, ptr)
}

#' Run (multithreaded) simulations
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#' @param n_replicates Integer. Number of independent simulation replicates to
#'   run.
#' @param n_threads Integer. Number of parallel threads to use for execution.
#' @param summarise Logical. Whether to summarize results across replicates
#'   (default: TRUE).
#' @param log_file Logical. Whether to write log output to a file (default:
#'   FALSE).
#' @param log_level String. Logging verbosity level.
#'
.SimulationConfig__run_simulations <- function(ptr, n_replicates, n_threads, summarise = TRUE, log_file = FALSE, log_level = "info") {
    invisible(.Call(`_amsimr_run_simulations`, ptr, n_replicates, n_threads, summarise, log_file, log_level))
}

