# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes correlation update when swapping pairs
#'
#' @param sol_mat Solution matrix
#' @param swap_idx Indices to swap
#' @param male_snp_idx Male SNP indices
#' @param female_snp_idx Female SNP indices
#' @return Correlation vector update
compute_delta <- function(sol_mat, swap_idx, male_snp_idx, female_snp_idx) {
    .Call('_amsim_compute_delta', PACKAGE = 'amsim', sol_mat, swap_idx, male_snp_idx, female_snp_idx)
}

#' Computes energy differential between states
#'
#' @param curr_cor Current correlation
#' @param target_cor Target correlation
#' @param delta_cor Correlation update
#' @return Energy differential
compute_dpsi <- function(curr_cor, target_cor, delta_cor) {
    .Call('_amsim_compute_dpsi', PACKAGE = 'amsim', curr_cor, target_cor, delta_cor)
}

#' Evaluates energy of current state
#'
#' @param curr_cor Current correlation
#' @param target_cor Target correlation
#' @return Energy value
compute_psi <- function(curr_cor, target_cor) {
    .Call('_amsim_compute_psi', PACKAGE = 'amsim', curr_cor, target_cor)
}

#' Performs simulated annealing to optimize matching
#'
#' @param sol_mat Solution matrix to optimize
#' @param snp_pairs SNP pair data [male_idx, female_idx, target_cor]
#' @param female_swap_idx Columns to swap in solution
#' @param max_iterations Maximum iterations to run
#' @param temp_decay Temperature decay rate
#' @param init_temp Initial temperature
#' @param collect_metrics Whether to collect optimization metrics
#' @return Optimized solution matrix and optional metrics
optim_matching <- function(sol_mat, snp_pairs, female_swap_idx, num_iterations = 10000L, temp_decay = 1.0, init_temp = 1.0, collect_metrics = FALSE) {
    .Call('_amsim_optim_matching', PACKAGE = 'amsim', sol_mat, snp_pairs, female_swap_idx, num_iterations, temp_decay, init_temp, collect_metrics)
}

