# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Copy a C-style array into a std::vector
#'
#' @param ptr Pointer to the first element of the source array.
#' @param n_elem Number of elements to copy.
#'
#' @return A std::vector containing a copy of the array elements.
#'
#' @noRd
NULL

#' Wrap a SimulationContext into an R-compatible list structure
#'
#' @details
#' Converts the internal C++ simulation context into a nested Rcpp::List
#' that can be passed to user-defined R metric functions. The resulting
#' list contains:
#' - n_individuals: Population size
#' - n_loci: Number of genetic loci
#' - n_phenotypes: Number of phenotypic traits
#' - n_sex: Number of individuals per sex
#' - genome: List with locus MAFs, means, and variances
#' - phenotypes: Named list of phenotype data (components, means, variances)
#' - mating: List containing mate matching state
#'
#' @param ctx Reference to the SimulationContext to wrap.
#'
#' @return An Rcpp::List containing the wrapped context data.
#'
#' @noRd
NULL

#' Wrap an R function into a thread-safe C++ MetricFunc
#'
#' @details
#' Creates a C++ lambda that wraps the provided R function, converting the
#' SimulationContext to an R list before invocation. A static mutex ensures
#' thread-safe access to the R runtime when running parallel simulations.
#'
#' @param r_func The R function to wrap. Must accept a list (simulation
#'   context) and return a numeric vector.
#'
#' @return A MetricFunc callable that invokes the R function with the
#'   wrapped context.
#'
#' @noRd
NULL

#' Create a custom metric specification
#'
#' @description
#' Defines a custom metric using an R function that computes values from the
#' simulation context. This allows users to extend the built-in metrics with
#' arbitrary calculations.
#'
#' @details
#' The provided R function receives a list containing the current simulation
#' state, including genome statistics, phenotype values and summary statistics,
#' and mating information. The function must return a numeric vector of length
#' `n_rows * n_cols`.
#'
#' The context list passed to the metric function contains:
#' \describe{
#'   \item{n_individuals}{Population size}
#'   \item{n_loci}{Number of genetic loci}
#'   \item{n_phenotypes}{Number of phenotypic traits}
#'   \item{n_sex}{Number of individuals per sex}
#'   \item{genome}{List with locus_mafs, locus_means, locus_vars}
#'   \item{phenotypes}{Named list of phenotype data with component vectors
#'     (genetic, environmental, vertical, total) and summary statistics}
#'   \item{mating}{List containing mate_matching state}
#' }
#'
#' @param name String. Unique identifier for the metric.
#' @param r_metric_func Function. An R function that accepts the simulation
#'   context list and returns a numeric vector.
#' @param r_n_rows Integer. Number of rows in the metric output.
#' @param r_n_cols Integer or NULL. Number of columns in the metric output
#'   (default: 1).
#' @param r_labels Character vector or NULL. Labels for metric components
#'   (default: empty).
#' @param require_lat Logical. Whether the metric requires linkage
#'   disequilibrium tracking (default: FALSE).
#'
#' @return An external pointer to a MetricSpec object for use with
#'   Simulation$metrics().
#'
custom_metric <- function(name, r_metric_func, r_n_rows, r_n_cols = NULL, r_labels = NULL, require_lat = FALSE) {
    .Call(`_amsimr_custom_metric`, name, r_metric_func, r_n_rows, r_n_cols, r_labels, require_lat)
}

#' Phenotype heritability metric
#'
#' @description
#' Creates a metric specification for tracking narrow-sense heritability
#' (h²) of each phenotype across generations.
#'
#' @return An external pointer to a MetricSpec object for use with
#'   Simulation$metrics().
#'
pheno_h2 <- function() {
    .Call(`_amsimr_pheno_h2`)
}

#' Phenotype component mean metric
#'
#' @description
#' Creates a metric specification for tracking the mean of a specific
#' phenotype component across generations.
#'
#' @param component_type String. The phenotype component to track. One of
#'   "genetic", "environmental", "vertical", or "total".
#'
#' @return An external pointer to a MetricSpec object for use with
#'   Simulation$metrics().
#'
pheno_comp_mean <- function(component_type) {
    .Call(`_amsimr_pheno_comp_mean`, component_type)
}

#' Phenotype component variance metric
#'
#' @description
#' Creates a metric specification for tracking the variance of a specific
#' phenotype component across generations.
#'
#' @param component_type String. The phenotype component to track. One of
#'   "genetic", "environmental", "vertical", or "total".
#'
#' @return An external pointer to a MetricSpec object for use with
#'   Simulation$metrics().
#'
pheno_comp_var <- function(component_type) {
    .Call(`_amsimr_pheno_comp_var`, component_type)
}

#' Phenotype component correlation metric
#'
#' @description
#' Creates a metric specification for tracking within-phenotype correlations
#' of a specific component across generations. This measures the correlation
#' matrix of the specified component across all phenotypes.
#'
#' @param component_type String. The phenotype component to track. One of
#'   "genetic", "environmental", "vertical", or "total".
#'
#' @return An external pointer to a MetricSpec object for use with
#'   Simulation$metrics().
#'
pheno_comp_cor <- function(component_type) {
    .Call(`_amsimr_pheno_comp_cor`, component_type)
}

#' Phenotype component cross-correlation metric
#'
#' @description
#' Creates a metric specification for tracking cross-mate correlations of a
#' specific phenotype component across generations. This measures the
#' correlation between mated pairs for the specified component.
#'
#' @param component_type String. The phenotype component to track. One of
#'   "genetic", "environmental", "vertical", or "total".
#'
#' @return An external pointer to a MetricSpec object for use with
#'   Simulation$metrics().
#'
pheno_comp_xcor <- function(component_type) {
    .Call(`_amsimr_pheno_comp_xcor`, component_type)
}

#' Latent phenotype heritability metric
#'
#' @description
#' Creates a metric specification for tracking narrow-sense heritability
#' (h²) of latent phenotype values across generations. Latent values
#' represent the underlying trait values before observation noise.
#'
#' @return An external pointer to a MetricSpec object for use with
#'   Simulation$metrics().
#'
pheno_latent_h2 <- function() {
    .Call(`_amsimr_pheno_latent_h2`)
}

#' Latent phenotype component mean metric
#'
#' @description
#' Creates a metric specification for tracking the mean of a specific
#' latent phenotype component across generations.
#'
#' @param component_type String. The phenotype component to track. One of
#'   "genetic", "environmental", "vertical", or "total".
#'
#' @return An external pointer to a MetricSpec object for use with
#'   Simulation$metrics().
#'
pheno_latent_comp_mean <- function(component_type) {
    .Call(`_amsimr_pheno_latent_comp_mean`, component_type)
}

#' Latent phenotype component variance metric
#'
#' @description
#' Creates a metric specification for tracking the variance of a specific
#' latent phenotype component across generations.
#'
#' @param component_type String. The phenotype component to track. One of
#'   "genetic", "environmental", "vertical", or "total".
#'
#' @return An external pointer to a MetricSpec object for use with
#'   Simulation$metrics().
#'
pheno_latent_comp_var <- function(component_type) {
    .Call(`_amsimr_pheno_latent_comp_var`, component_type)
}

#' Latent phenotype component correlation metric
#'
#' @description
#' Creates a metric specification for tracking within-phenotype correlations
#' of a specific latent component across generations.
#'
#' @param component_type String. The phenotype component to track. One of
#'   "genetic", "environmental", "vertical", or "total".
#'
#' @return An external pointer to a MetricSpec object for use with
#'   Simulation$metrics().
#'
pheno_latent_comp_cor <- function(component_type) {
    .Call(`_amsimr_pheno_latent_comp_cor`, component_type)
}

#' Latent phenotype component cross-correlation metric
#'
#' @description
#' Creates a metric specification for tracking cross-mate correlations of a
#' specific latent phenotype component across generations.
#'
#' @param component_type String. The phenotype component to track. One of
#'   "genetic", "environmental", "vertical", or "total".
#'
#' @return An external pointer to a MetricSpec object for use with
#'   Simulation$metrics().
#'
pheno_latent_comp_xcor <- function(component_type) {
    .Call(`_amsimr_pheno_latent_comp_xcor`, component_type)
}

#' Create a new SimulationResults object reference
#'
#' @return A new SimulationResults instance.
#'
.SimulationResults_new <- function(output_dir) {
    .Call(`_amsimr_SimulationResults_new`, output_dir)
}

#' Perform summarisation on replicate metric data
#'
#' @param ptr An external pointer to a SimulationResults instance.
#'
.SimulationResults_summarise <- function(ptr) {
    invisible(.Call(`_amsimr_SimulationResults_summarise`, ptr))
}

#' Save summarised results to disk
#'
#' @param ptr An external pointer to a SimulationResults instance.
#' @param metrics A list of metric names to be saved to file.
#' @param out_dir Output directory to write data out to.
#' @param overwrite Specifies whether directory should be overwritten.
#'
.SimulationResults_save <- function(ptr, metrics = NULL, out_dir = NULL, overwrite = FALSE) {
    invisible(.Call(`_amsimr_SimulationResults_save`, ptr, metrics, out_dir, overwrite))
}

#' Load a summarised metric into the binding layer.
#'
#' @param ptr An external pointer to a SimulationResults instance.
#' @param metric_name Name of the metric to be loaded into the environment.
#'
#' @return A DataFrame comprising the summarised results data for the specified
#'   metric.
#'
.SimulationResults_load <- function(ptr, metric_name) {
    .Call(`_amsimr_SimulationResults_load`, ptr, metric_name)
}

#' Get metric names
#'
#' @param ptr An external pointer to a SimulationResults instance.
#'
#' @return A vector of the metric names recognised by the results instance.
#'
.SimulationResults_metric_names <- function(ptr) {
    .Call(`_amsimr_SimulationResults_metric_names`, ptr)
}

#' Create a new SimulationConfig object reference
#'
#' @return A new SimulationConfig instance.
#'
.SimulationConfig_new <- function() {
    .Call(`_amsimr_SimulationConfig_new`)
}

#' Configure simulation parameters
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#' @param n_generations Integer. Number of generations to simulate.
#' @param n_individuals Integer. Number of individuals in the population.
#' @param output_dir String. Output directory to write data out to.
#' @param random_seed Integer. Seed used by random number generator.
#'
#' @return Self, for method chaining.
#'
.SimulationConfig_simulation <- function(ptr, n_generations, n_individuals, output_dir, random_seed) {
    .Call(`_amsimr_SimulationConfig_simulation`, ptr, n_generations, n_individuals, output_dir, random_seed)
}

#' Configure genome parameters
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#' @param n_loci Number of genetic loci simulated in the population.
#' @param locus_maf Vector of locus MAFs.
#' @param locus_recombination Vector of locus recombination probabilities.
#' @param locus_mutation Vector of locus mutation probabilities.
#'
#' @return Self, for method chaining.
#'
.SimulationConfig_genome <- function(ptr, n_loci, locus_maf, locus_recombination, locus_mutation) {
    .Call(`_amsimr_SimulationConfig_genome`, ptr, n_loci, locus_maf, locus_recombination, locus_mutation)
}

#' Configure phenome parameters
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#' @param n_phenotypes Number of phenotypes modelled in the population.
#' @param names Vector of phenotype names.
#' @param n_causal_loci Number of causal loci for each phenotype.
#' @param h2_genetic Narrow-sense phenotype heritabilities.
#' @param h2_environmental Phenotype environmental component variances.
#' @param h2_vertical Phenotype vertical component variances.
#' @param genetic_cor Genetic correlation matrix (column-major).
#' @param environmental_cor Environmental correlation matrix (column-major).
#'
#' @return Self, for method chaining.
#'
.SimulationConfig_phenome <- function(ptr, n_phenotypes, names, n_causal_loci, h2_genetic, h2_environmental, h2_vertical, genetic_cor, environmental_cor) {
    .Call(`_amsimr_SimulationConfig_phenome`, ptr, n_phenotypes, names, n_causal_loci, h2_genetic, h2_environmental, h2_vertical, genetic_cor, environmental_cor)
}

#' Specify a random mating regime
#'
#' @return Self, for method chaining.
#'
.SimulationConfig_random_mating <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_random_mating`, ptr)
}

#' Specify an assortative mating regime
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#' @param mate_cor Column-major double trait cross-correlation matrix.
#' @param tol_inf Termination threshold for annealing routine.
#' @param n_iterations Maximum number of steps performed in annealing routine.
#' @param temp_init Initial temperature of annealing routine.
#' @param temp_decay Temperature decay parameter of annealing routine.
#'
#' @return Self, for method chaining
#'
.SimulationConfig_assortative_mating <- function(ptr, mate_cor, tol_inf = NULL, n_iterations = NULL, temp_init = NULL, temp_decay = NULL) {
    .Call(`_amsimr_SimulationConfig_assortative_mating`, ptr, mate_cor, tol_inf, n_iterations, temp_init, temp_decay)
}

#' Configure simulation metrics
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#' @param metrics List of metric objects to attach to the simulation.
#'
#' @return Self, for method chaining.
#'
.SimulationConfig_metrics <- function(ptr, metrics) {
    .Call(`_amsimr_SimulationConfig_metrics`, ptr, metrics)
}

#' Get the number of generations
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Integer specifying the number of generations to simulate.
#'
.SimulationConfig_n_generations <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_n_generations`, ptr)
}

#' Get the number of individuals
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Integer specifying the population size.
#'
.SimulationConfig_n_individuals <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_n_individuals`, ptr)
}

#' Get the number of loci
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Integer specifying the number of genetic loci.
#'
.SimulationConfig_n_loci <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_n_loci`, ptr)
}

#' Get the output directory
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return String specifying the output directory path.
#'
.SimulationConfig_output_dir <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_output_dir`, ptr)
}

#' Get the RNG seed
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Integer specifying the random number generator seed.
#'
.SimulationConfig_random_seed <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_random_seed`, ptr)
}

#' Get the locus MAF vector
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Numeric vector of minor allele frequencies for each locus.
#'
.SimulationConfig_locus_maf <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_locus_maf`, ptr)
}

#' Get the locus recombination probabilities
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Numeric vector of recombination probabilities for each locus.
#'
.SimulationConfig_locus_recombination <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_locus_recombination`, ptr)
}

#' Get the locus mutation probabilities
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Numeric vector of mutation probabilities for each locus.
#'
.SimulationConfig_locus_mutation <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_locus_mutation`, ptr)
}

#' Get the number of phenotypes
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Integer specifying the number of phenotypic traits.
#'
.SimulationConfig_n_phenotypes <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_n_phenotypes`, ptr)
}

#' Get the phenotype names
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Character vector of phenotype names.
#'
.SimulationConfig_phenotype_names <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_phenotype_names`, ptr)
}

#' Get the number of causal loci for each phenotype
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Integer vector specifying the number of causal loci per phenotype.
#'
.SimulationConfig_n_causal_loci <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_n_causal_loci`, ptr)
}

#' Get the narrow-sense phenotype heritabilities
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Numeric vector of narrow-sense heritabilities for each phenotype.
#'
.SimulationConfig_h2_genetic <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_h2_genetic`, ptr)
}

#' Get the phenotype environmental component variances
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Numeric vector of environmental variance components for each
#'   phenotype.
#'
.SimulationConfig_h2_environmental <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_h2_environmental`, ptr)
}

#' Get the phenotype vertical component variances
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Numeric vector of vertical transmission components for each
#'   phenotype.
#'
.SimulationConfig_h2_vertical <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_h2_vertical`, ptr)
}

#' Get the phenotype genetic component correlation matrix
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Numeric vector representing the genetic correlation matrix in
#'   column-major order.
#'
.SimulationConfig_genetic_cor <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_genetic_cor`, ptr)
}

#' Get the phenotype environmental component correlation matrix
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Numeric vector representing the environmental correlation matrix in
#'   column-major order.
#'
.SimulationConfig_environmental_cor <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_environmental_cor`, ptr)
}

#' Get the mating correlation matrix
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Numeric vector representing the mating correlation matrix in
#'   column-major order.
#'
.SimulationConfig_mate_cor <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_mate_cor`, ptr)
}

#' Get the annealing tolerance threshold
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Numeric value specifying the termination threshold for the
#'   annealing routine.
#'
.SimulationConfig_tol_inf <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_tol_inf`, ptr)
}

#' Get the maximum number of annealing iterations
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Integer specifying the maximum number of annealing iterations.
#'
.SimulationConfig_n_iterations <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_n_iterations`, ptr)
}

#' Get the initial annealing temperature
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Numeric value specifying the initial annealing temperature.
#'
.SimulationConfig_temp_init <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_temp_init`, ptr)
}

#' Get the annealing temperature decay parameter
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#'
#' @return Numeric value specifying the temperature decay rate.
#'
.SimulationConfig_temp_decay <- function(ptr) {
    .Call(`_amsimr_SimulationConfig_temp_decay`, ptr)
}

#' Run (multithreaded) simulations
#'
#' @param ptr An external pointer to a SimulationConfig instance.
#' @param n_replicates Integer. Number of independent simulation replicates to
#'   run.
#' @param n_threads Integer. Number of parallel threads to use for execution.
#' @param summarise Logical. Whether to summarize results across replicates
#'   (default: TRUE).
#' @param log_file Logical. Whether to write log output to a file (default:
#'   FALSE).
#' @param log_level String. Logging verbosity level.
#'
.run_simulations <- function(ptr, n_replicates, n_threads, summarise = TRUE, log_file = FALSE, log_level = "info") {
    invisible(.Call(`_amsimr_run_simulations`, ptr, n_replicates, n_threads, summarise, log_file, log_level))
}

